version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - ./api/.env
    volumes:
      - ./api:/app

  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - ./client/.env
    depends_on:
      - api

networks:
  api-network:
    driver: bridge
